### ISSUE TITLE
Please update schematic, adding POWER_SWITCH changes

### ISSUE THREAD

**Issue by urish** [adafruit/Adafruit-Circuit-Playground-Bluefruit-PCB#1]
We're looking to include some Bluefruit boards in our next [CircuitPython Workshop](https://www.meetup.com/IoT-Makers-Israel/events/267224629/). 

They are not available for purchase on DigiKey Israel, and out of stock on Adafruit's site, so we're considering making a small batch of the PCB and assembling here, especially for the workshop. 

By making our batch we will also be able to put sponsor logo on the PCB (making it easier for us to find a sponsor), and perhaps also upgrade to Micro USB to USB Type-C port. We will share the modified version, respecting the [terms of the license](https://github.com/adafruit/Adafruit-Circuit-Playground-Bluefruit-PCB/blob/b482caa5d5163efdda080e9e892c69210677a284/license.txt), of course.

Can you please update the board eagle files with the latest revision, with the [`POWER_SWITCH` pin](https://github.com/adafruit/circuitpython/blob/3dc98a7a795fd93dce7fb133cf504cd8dffb882d/ports/nrf/boards/circuitplayground_bluefruit/pins.c#L52)?

Your help here will be greatly appreciated!

**Comment by kattni** [comment]
@urish I've uploaded the latest rev of the board.

**Comment by urish** [comment]
Thank you so much @kattni !

**Comment by kattni** [comment]
@urish You're entirely welcome :)
